import type { ConflictConfig } from './types';

// تئاتر ایران/اسرائیل — پیکربندی اصلی IRONSIGHT
// تمام مقادیر از کد سخت‌شده اصلی استخراج شدند تا داشبورد به‌طور یکسان رندر شود

export const iranIsrael: ConflictConfig = {
  key: 'iran-israel',
  label: 'ایران / اسرائیل',
  theater: 'مرکز فرماندهی اطلاعات / غیرطبقه‌بندی‌شده',

  client: {
    mapCenter: [30.0, 48.0],
    mapZoom: 5,

    cities: [
      { name: 'تهران', lat: 35.6892, lon: 51.3890, country: 'ایران', capital: true },
      { name: 'اصفهان', lat: 32.6546, lon: 51.6680, country: 'ایران', capital: false },
      { name: 'شیراز', lat: 29.5918, lon: 52.5837, country: 'ایران', capital: false },
      { name: 'تبریز', lat: 38.0800, lon: 46.2919, country: 'ایران', capital: false },
      { name: 'بندرعباس', lat: 27.1865, lon: 56.2808, country: 'ایران', capital: false },
      { name: 'تل‌آویو', lat: 32.0853, lon: 34.7818, country: 'اسرائیل', capital: false },
      { name: 'بیت‌المقدس', lat: 31.7683, lon: 35.2137, country: 'اسرائیل', capital: true },
      { name: 'حیفا', lat: 32.7940, lon: 34.9896, country: 'اسرائیل', capital: false },
      { name: 'بغداد', lat: 33.3152, lon: 44.3661, country: 'عراق', capital: true },
      { name: 'دمشق', lat: 33.5138, lon: 36.2765, country: 'سوریه', capital: true },
      { name: 'بیروت', lat: 33.8938, lon: 35.5018, country: 'لبنان', capital: true },
      { name: 'ریاض', lat: 24.7136, lon: 46.6753, country: 'عربستان سعودی', capital: true },
      { name: 'دبی', lat: 25.2048, lon: 55.2708, country: 'امارات', capital: false },
      { name: 'دوحه', lat: 25.2854, lon: 51.5310, country: 'قطر', capital: true },
      { name: 'منامه', lat: 26.2285, lon: 50.5860, country: 'بحرین', capital: true },
      { name: 'کویت', lat: 29.3759, lon: 47.9774, country: 'کویت', capital: true },
      { name: 'عمّان', lat: 31.9454, lon: 35.9284, country: 'اردن', capital: true },
      { name: 'قاهره', lat: 30.0444, lon: 31.2357, country: 'مصر', capital: true },
      { name: 'انقره', lat: 39.9334, lon: 32.8597, country: 'ترکیه', capital: true },
      { name: 'صنعاء', lat: 15.3694, lon: 44.1910, country: 'یمن', capital: true },
      { name: 'عدن', lat: 12.7855, lon: 45.0187, country: 'یمن', capital: false },
      { name: 'مسقط', lat: 23.5880, lon: 58.3829, country: 'عمان', capital: true },
      { name: 'دیمونا', lat: 31.0700, lon: 35.0300, country: 'اسرائیل', capital: false },
    ],

    cityColors: { 'ایران': '#ff6666', 'اسرائیل': '#66ccff', default: '#999999' },

    launchSites: [
      { name: 'پایگاه سپاه تبریز', lat: 38.08, lon: 46.29, range: 2000 },
      { name: 'پایگاه موشکی اصفهان', lat: 32.65, lon: 51.67, range: 2000 },
      { name: 'پایگاه هوایی شیراز', lat: 29.54, lon: 52.59, range: 1800 },
      { name: 'پایگاه خرم‌آباد', lat: 33.49, lon: 48.35, range: 2000 },
    ],

    strikeLocations: {
      // اهداف ایران
      'تهران': [35.69, 51.39], 'اصفهان': [32.65, 51.67], 'ناتنز': [33.51, 51.73],
      'شیراز': [29.59, 52.58], 'تبریز': [38.08, 46.29], 'بوشهر': [28.97, 50.84],
      'بندرعباس': [27.19, 56.28], 'جزیره خارگ': [29.24, 50.31], 'پارس جنوبی': [27.5, 52.6],
      'ایران': [32.5, 53.0],
      // اهداف اسرائیل
      'تل‌آویو': [32.09, 34.78], 'حیفا': [32.79, 34.99], 'دیمونا': [31.07, 35.03],
      'بیت‌المقدس': [31.77, 35.21], 'بئرشبع': [31.25, 34.79], 'ایلات': [29.56, 34.95],
      'نگوو': [30.85, 34.78], 'عراد': [31.26, 35.21], 'اشدود': [31.80, 34.66],
      'اشکلون': [31.67, 34.57], 'فرودگاه بن‌گوریون': [32.01, 34.87], 'هسته‌ای': [31.07, 35.03],
      'اسرائیل': [31.5, 34.8],
      // لبنان
      'بیروت': [33.89, 35.50], 'حزب‌الله': [33.60, 35.50], 'لیتانی': [33.35, 35.30],
      'جنوب لبنان': [33.30, 35.40], 'لبنان': [33.85, 35.86],
      // سایر نقاط
      'سوریه': [34.80, 38.99], 'دمشق': [33.51, 36.28],
      'عراق': [33.31, 44.37], 'بغداد': [33.31, 44.37],
      'یمن': [15.37, 44.19], 'انصارالله': [15.37, 44.19], 'دریای سرخ': [14.5, 42.5],
      'غزه': [31.42, 34.36], 'تنگه هرمز': [26.56, 56.25],
      'قطر': [25.29, 51.53], 'دوحه': [25.29, 51.53],
      'عربستان': [24.71, 46.68], 'دیاگو گارسیا': [-7.32, 72.42],
      'کویت': [29.38, 47.98],
    },

    strikeTargets: [
      // اهداف اسرائیل
      ['عراد', 'عراد'], ['دیمونا', 'دیمونا'], ['ناتنز', 'ناتنز'], ['فرودگاه بن‌گوریون', 'فرودگاه بن‌گوریون'],
      ['تل‌آویو', 'تل‌آویو'], ['حیفا', 'حیفا'], ['بئرشبع', 'بئرشبع'], ['ایلات', 'ایلات'],
      ['اشکلون', 'اشکلون'], ['اشدود', 'اشدود'], ['نگوو', 'نگوو'], ['صدیروت', 'صدیروت'],
      ['بیت‌المقدس', 'بیت‌المقدس'], ['شهر هسته‌ای', 'دیمونا'],
      // اهداف ایران
      ['تهران', 'تهران'], ['اصفهان', 'اصفهان'], ['شیراز', 'شیراز'], ['تبریز', 'تبریز'],
      ['بندرعباس', 'بندرعباس'], ['بوشهر', 'بوشهر'], ['جزیره خارگ', 'جزیره خارگ'],
      ['پارس جنوبی', 'پارس جنوبی'],
      // لبنان
      ['بیروت', 'بیروت'], ['رودخانه لیتانی', 'رودخانه لیتانی'], ['جنوب لبنان', 'جنوب لبنان'],
      // سایر
      ['دمشق', 'دمشق'], ['بغداد', 'بغداد'], ['دیاگو گارسیا', 'دیاگو گارسیا'],
      ['تنگه هرمز', 'تنگه هرمز'], ['دریای سرخ', 'دریای سرخ'],
      ['غزه', 'غزه'], ['دوحه', 'دوحه'], ['کویت', 'کویت'],
    ],

    alertCities: {
      'تل‌آویو': [32.085, 34.782], 'حیفا': [32.794, 34.990], 'بیت‌المقدس': [31.768, 35.214],
      'بئرشبع': [31.252, 34.791], 'اشکلون': [31.669, 34.574], 'اشدود': [31.804, 34.655],
      'صدیروت': [31.525, 34.596], 'ایلات': [29.558, 34.952], 'طبریه': [32.796, 35.530],
      'نهاریه': [33.010, 35.098], 'دیمونا': [31.070, 35.030], 'عراد': [31.261, 35.213],
    },

    alertFallbackCenter: [31.5, 34.8],
    defaultMissileOrigin: [33.5, 48.0],
    missileOrigins: [
      { match: 'لبنان', coords: [33.89, 35.50] },
      { match: 'حزب‌الله', coords: [33.89, 35.50] },
    ],

    flightColors: [
      { match: 'US', color: '#00aaff' },
      { match: 'ایالات‌متحده', color: '#00aaff' },
      { match: 'اسرائیل', color: '#00d4ff' },
      { match: 'ایران', color: '#ff3366' },
      { match: 'UK', color: '#4488cc' },
      { match: 'سلطنتی', color: '#4488cc' },
    ],

    navyColors: {
      'نیروی دریایی ایالات‌متحده': '#00aaff', 'نیروی دریایی سلطنتی': '#4488cc', 'نیروی دریایی فرانسه': '#6666cc',
      'نیروی دریایی اسرائیل': '#00d4ff', 'نیروی دریایی ایران': '#ff3366', 'نیروی دریایی سپاه': '#ff3366', 'نیروی دریایی عربستان': '#00ff88',
    },

    timeZones: [
      { label: 'DC', zone: 'America/New_York', flag: '🇺🇸' },
      { label: 'LON', zone: 'Europe/London', flag: '🇬🇧' },
      { label: 'TLV', zone: 'Asia/Jerusalem', flag: '🇮🇱' },
      { label: 'THR', zone: 'Asia/Tehran', flag: '🇮🇷' },
      { label: 'RYD', zone: 'Asia/Riyadh', flag: '🇸🇦' },
      { label: 'MSK', zone: 'Asia/Shanghai', flag: '🇨🇳' },
    ],

    sourceColors: {
      'Reuters': '#ff8000', 'AP': '#ff2222', 'BBC': '#bb1919', 'NYT': '#333',
      'Al Jazeera': '#d4a843', 'Times of Israel': '#0066cc', 'JPost': '#003366',
      'CNN': '#cc0000', 'Fox News': '#003366', 'WSJ': '#0274b6', 'The National': '#1a6b3c',
      'PressTV': '#00a650', 'Breaking Def': '#cc0000', 'Long War Jrnl': '#556b2f',
      'Mil Times': '#8b0000', 'War on Rocks': '#2e4057', 'CENTCOM': '#4b5320',
      'DoD': '#003366', 'Haaretz': '#2a7fff', 'Drop Site': '#e63946', 'Ynet': '#f44336',
      'N12': '#e91e63', 'Walla': '#ff5722', 'Google News': '#4285f4',
    },

    navyOrder: ['نیروی دریایی ایالات‌متحده', 'نیروی دریایی سلطنتی', 'نیروی دریایی فرانسه', 'نیروی دریایی اسرائیل', 'نیروی دریایی عربستان', 'نیروی دریایی ایران', 'نیروی دریایی سپاه'],
    maritimeRegions: ['خلیج‌فارس', 'دریای سرخ', 'مدیترانه شرقی', 'تنگه هرمز'],

    countryColors: {
      'لبنان': '#e06030', 'ایران': '#cc3355', 'عراق': '#cc8833', 'سوریه': '#aa7744',
      'یمن': '#55aa55', 'کویت': '#44bbaa', 'بحرین': '#dd6699', 'امارات': '#8866cc',
      'عربستان سعودی': '#33aa77', 'قطر': '#7744aa', 'اردن': '#4488cc',
    },

    regionBoxes: [
      { name: 'ترکیه', latMin: 36, latMax: 90, lonMin: 36, lonMax: 45 },
      { name: 'اسرائیل', latMin: 29, latMax: 34, lonMin: 34, lonMax: 36 },
      { name: 'ایران', latMin: 24, latMax: 38, lonMin: 44, lonMax: 64 },
      { name: 'عراق', latMin: 29, latMax: 38, lonMin: 38, lonMax: 49 },
      { name: 'سوریه', latMin: 32, latMax: 38, lonMin: 35, lonMax: 43 },
      { name: 'لبنان', latMin: 33, latMax: 35, lonMin: 35, lonMax: 37 },
      { name: 'یمن', latMin: 12, latMax: 19, lonMin: 42, lonMax: 55 },
      { name: 'عربستان سعودی', latMin: 16, latMax: 33, lonMin: 34, lonMax: 56 },
      { name: 'امارات', latMin: 22, latMax: 27, lonMin: 51, lonMax: 57 },
      { name: 'مصر', latMin: 25, latMax: 31, lonMin: 25, lonMax: 35 },
      { name: 'اردن', latMin: 30, latMax: 34, lonMin: 35, lonMax: 40 },
      { name: 'قطر/بحرین', latMin: 23, latMax: 27, lonMin: 45, lonMax: 51 },
      { name: 'عمان', latMin: 21, latMax: 27, lonMin: 55, lonMax: 60 },
    ],
    defaultRegion: 'خاورمیانه',

    alertSystemName: 'سیستم هشدار اسرائیل',
    alertStatusTitle: 'وضعیت هشدار اسرائیل',
    hasDroneTracker: false,
  },

  server: {
    strikeQueries: [
      'ایران+OR+اسرائیل+موشک+حمله+OR+حمله+هوایی+OR+رهگیری',
      'ایران+OR+اسرائیل+پهپاد+حمله+OR+پرتاب+موشک',
    ],
    countryAttribution: [
      { match: ['ایران', 'تهران'], country: 'ایران' },
      { match: ['اسرائیل'], country: 'اسرائیل' },
      { match: ['لبنان'], country: 'لبنان' },
      { match: ['سوریه'], country: 'سوریه' },
      { match: ['یمن', 'انصارالله'], country: 'یمن' },
    ],
    defaultCountry: 'خاورمیانه',

    conflictQueries: [
      'ایران اسرائیل جنگ نظامی درگیری حمله',
      'موشک OR راکت OR پهپاد حمله OR حمله عراد OR دیمونا OR تل‌آویو OR حیفا OR ایلات OR تهران OR اصفهان OR بیروت OR پارس جنوبی OR ناتنز OR دیاگو گارسیا',
    ],
    conflictLocations: [
      { match: ['عراد'], location: 'عراد، اسرائیل' },
      { match: ['دیمونا', 'شهر هسته‌ای'], location: 'دیمونا، اسرائیل' },
      { match: ['تل‌آویو'], location: 'تل‌آویو، اسرائیل' },
      { match: ['حیفا'], location: 'حیفا، اسرائیل' },
      { match: ['ایلات'], location: 'ایلات، اسرائیل' },
      { match: ['اشکلون'], location: 'اشکلون، اسرائیل' },
      { match: ['اشدود'], location: 'اشدود، اسرائیل' },
      { match: ['نگوو'], location: 'نگوو، اسرائیل' },
      { match: ['ناتنز'], location: 'ناتنز، ایران' },
      { match: ['اصفهان'], location: 'اصفهان، ایران' },
      { match: ['تهران'], location: 'تهران، ایران' },
      { match: ['پارس جنوبی'], location: 'پارس جنوبی، ایران' },
      { match: ['بوشهر'], location: 'بوشهر، ایران' },
      { match: ['تبریز'], location: 'تبریز، ایران' },
      { match: ['بیروت'], location: 'بیروت، لبنان' },
      { match: ['لبنان'], location: 'لبنان' },
      { match: ['دمشق'], location: 'دمشق، سوریه' },
      { match: ['سوریه'], location: 'سوریه' },
      { match: ['بغداد'], location: 'بغداد، عراق' },
      { match: ['عراق'], location: 'عراق' },
      { match: ['دیاگو گارسیا'], location: 'دیاگو گارسیا' },
      { match: ['قطر', 'دوحه'], location: 'قطر' },
      { match: ['کویت'], location: 'کویت' },
      { match: ['عربستان'], location: 'عربستان سعودی' },
      { match: ['یمن', 'انصارالله'], location: 'یمن' },
      { match: ['غزه'], location: 'غزه' },
      { match: ['اسرائیل'], location: 'اسرائیل' },
      { match: ['ایران'], location: 'ایران' },
    ],

    countryQueries: [
      { country: 'لبنان', flag: '🇱🇧', query: 'لبنان+حمله+OR+حمله‌هوایی+OR+حمله+OR+موشک+OR+بمب+OR+حزب‌الله+OR+حمله‌بیروت' },
      { country: 'ایران', flag: '🇮🇷', query: 'ایران+حمله+OR+حمله+OR+موشک+OR+بمب+OR+حمله‌تهران+OR+حمله‌سپاه' },
      { country: 'عراق', flag: '🇮🇶', query: 'عراق+حمله+OR+حمله+OR+موشک+OR+حمله‌بغداد+OR+حمله‌نیروهای+شبه‌نظامی' },
      { country: 'سوریه', flag: '🇸🇾', query: 'سوریه+حمله+OR+حمله‌هوایی+OR+حمله+OR+حمله‌دمشق' },
      { country: 'یمن', flag: '🇾🇪', query: 'یمن+انصارالله+حمله+OR+حمله+OR+موشک+OR+پهپاد+OR+دریای+سرخ+حمله' },
      { country: 'کویت', flag: '🇰🇼', query: 'کویت+آژیر+OR+موشک+OR+حمله+OR+دفاع‌هوایی+OR+رهگیری' },
      { country: 'بحرین', flag: '🇧🇭', query: 'بحرین+حمله+OR+موشک+OR+نظامی+OR+تهدید+OR+ناوگان‌پنجم' },
      { country: 'امارات', flag: '🇦🇪', query: 'امارات+OR+دبی+OR+ابوظبی+حمله+OR+موشک+OR+پهپاد+OR+رهگیری' },
      { country: 'عربستان سعودی', flag: '🇸🇦', query: 'عربستان+حمله+OR+موشک+OR+پهپاد+OR+رهگیری+OR+انصارالله' },
      { country: 'اردن', flag: '🇯🇴', query: 'اردن+حمله+OR+موشک+OR+رهگیری+OR+حریم+هوایی+OR+نظامی' },
    ],

    polymarketKeywords: /\bایران\b|اسرائیل|خاورمیانه|آتش‌بس|نظامی.*ایران|نظامی.*اسرائیل|\bجنگ\b.*(?:ایران|اسرائیل|خاورمیانه)|حمله.*(?:ایران|اسرائیل)|موشک|هسته.*ایران|غزه|حزب‌الله|انصارالله|لبنان.*(?:حمله|تهاجم|تجاوز)|سوریه.*حمله|یمن.*(?:حمله|حمله)|هرمز|دریای.*سرخ.*(?:حمله|نظامی)|idf\b|irgc\b|نتانیاهو|خامنه|ترامپ.*ایران|رژیم.*(?:سقوط|تغییر)|حمله.*زمینی|حمله.*هوایی|پهپاد.*(?:ایران|اسرائیل|حمله)|بالستیک/i,
    polymarketExclude: /nba|nfl|mlb|nhl|fifa|جام.*جهانی|لیگ.*برتر|چمپیونز|سوپر.*باول|اسکار|گرمی|امی|انتخابات.*فرماندار|شهردار|warriors|lakers|celtics|yankees|dodgers|روسیه|اوکراین|چین|تایوان|کره.*شمالی|تعرفه|کریپتو|بیت‌کوین|اتریوم|سولانا/i,

    firesBBox: { latMin: 20, latMax: 42, lonMin: 25, lonMax: 65 },

    flightsCenter: { lat: 30, lon: 48, dist: 2500 },
    flightsBBox: { latMin: 10, latMax: 45, lonMin: 20, lonMax: 70 },

    newsFeeds: [
      { url: 'https://feeds.bbci.co.uk/news/world/middle_east/rss.xml', name: 'BBC', unfiltered: true },
      { url: 'https://rss.nytimes.com/services/xml/rss/nyt/MiddleEast.xml', name: 'NYT', unfiltered: true },
      { url: 'https://www.aljazeera.com/xml/rss/all.xml', name: 'Al Jazeera' },
      { url: 'https://feeds.reuters.com/Reuters/worldNews', name: 'Reuters' },
      { url: 'https://www.timesofisrael.com/feed/', name: 'Times of Israel', unfiltered: true },
      { url: 'https://www.jpost.com/rss/rssfeedsfrontpage.aspx', name: 'JPost', unfiltered: true },
      { url: 'https://www.ynetnews.com/Integration/StoryRss2.xml', name: 'Ynet', unfiltered: true },
      { url: 'https://rcs.mako.co.il/rss/news-military.xml', name: 'N12', unfiltered: true },
      { url: 'https://rss.walla.co.il/feed/22', name: 'Walla', unfiltered: true },
      { url: 'https://www.thenationalnews.com/arc/outboundfeeds/rss/?outputType=xml', name: 'The National' },
      { url: 'http://rss.cnn.com/rss/edition_meast.rss', name: 'CNN' },
      { url: 'https://moxie.foxnews.com/google-publisher/world.xml', name: 'Fox News' },
      { url: 'https://feeds.content.dowjones.io/public/rss/RSSWorldNews', name: 'WSJ' },
      { url: 'https://news.google.com/rss/search?q=Iran+Israel+war+military&hl=en-US&gl=US&ceid=US:en', name: 'Google News', unfiltered: true },
      { url: 'https://news.google.com/rss/search?q=Iran+missile+strike+drone&hl=en-US&gl=US&ceid=US:en', name: 'Google News', unfiltered: true },
      { url: 'https://news.google.com/rss/search?q=%22Strait+of+Hormuz%22+OR+%22Red+Sea%22+military&hl=en-US&gl=US&ceid=US:en', name: 'Google News', unfiltered: true },
      { url: 'https://breakingdefense.com/feed/', name: 'Breaking Def' },
      { url: 'https://www.longwarjournal.org/feed', name: 'Long War Jrnl' },
      { url: 'https://www.militarytimes.com/arc/outboundfeeds/rss/?outputType=xml', name: 'Mil Times' },
      { url: 'https://warontherocks.com/feed/', name: 'War on Rocks' },
      { url: 'https://www.centcom.mil/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=808&max=20', name: 'CENTCOM', unfiltered: true },
      { url: 'https://www.defense.gov/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=945&max=10', name: 'DoD', unfiltered: true },
      { url: 'https://www.haaretz.com/srv/haaretz-latest-headlines', name: 'Haaretz', unfiltered: true },
      { url: 'https://www.haaretz.com/srv/middle-east-news-rss', name: 'Haaretz', unfiltered: true },
      { url: 'https://www.dropsitenews.com/feed', name: 'Drop Site' },
      { url: 'https://www.presstv.ir/rss.xml', name: 'PressTV', unfiltered: true },
      { url: 'https://www.presstv.ir/rss/rss-102.xml', name: 'PressTV', unfiltered: true },
      { url: 'https://www.presstv.ir/rss/rss-101.xml', name: 'PressTV', unfiltered: true },
    ],
    newsRelevanceKeywords: /ایران|اسرائیل|idf|irgc|حزب‌الله|حماس|انصارالله|لبنان|غزه|تهران|تل\s?آویو|بیت‌المقدس|یمن|عراق|سوریه|خلیج|هرمز|دریای\s?سرخ|موشک|حمله|رهگیری|هسته|تحریم|centcom|pentagon|خاورمیانه|کرانه.*باختری|جولان|سینا|نگوو|دیمونا|ناتنز|اصفهان|خامنه|نتانیاهو|نصرالله|رئیسی|آیت‌الله|موساد|شین‌بت|قدس|بسیج|توکل|سقوط|تغییر|حمله.*زمینی|حمله.*هوایی|پهپاد.*(?:ایران|اسرائیل|حمله)|بالستیک|عربستان|امارات|uae|بحرین|قطر|کویت|عمان|gcc|opec/i,

    telegramChannels: [
      { name: 'IDFofficial', label: 'اطلاعات رسمی ارتش', color: '#3388ff' },
      { name: 'RocketAlert', label: 'هشدار راکت', color: '#ff3366' },
      { name: 'PressTV', label: 'پرس‌تی‌وی (ایران)', color: '#cc3333' },
      { name: 'OSINTdefender', label: 'دفاع اطلاعات', color: '#00aaff' },
      { name: 'middle_east_spectator', label: 'ناظر خاورمیانه', color: '#ff6600' },
      { name: 'iranintl_en', label: 'ایران اینترنشنل', color: '#00ff88' },
      { name: 'Alertisrael', label: 'هشدار اسرائیل', color: '#ff6688' },
      { name: 'QudsNen', label: 'اخبار قدس', color: '#33cc66' },
      { name: 'TimesofIsrael', label: 'اوقات اسرائیل', color: '#0066cc' },
      { name: 'FarsNews_EN', label: 'اخبار فارس', color: '#669933' },
      { name: 'FotrosResistancee', label: 'فتروس مقاومت', color: '#dd4444' },
      { name: 'Alsaa_plus_EN', label: 'السَّاعة', color: '#ee8833' },
      { name: 'warfareanalysis', label: 'تحلیل جنگی', color: '#8888cc' },
      { name: 'rnintel', label: 'اطلاعات RN', color: '#44aacc' },
      { name: 'GeoPWatch', label: 'نظارت ژئوپولتیک', color: '#cc66aa' },
      { name: 'thecradlemedia', label: 'رسانه گهواره', color: '#aa8844' },
      { name: 'Middle_East_Spectator', label: 'ناظر خاورمیانه ۲', color: '#ff8844' },
      { name: 'HAMASW', label: 'جنگ حماس-اسرائیل', color: '#339933' },
      { name: 'TasnimNewsEN', label: 'اخبار تسنیم', color: '#557733' },
      { name: 'AbuAliExpress', label: 'ابوعلی اکسپرس', color: '#dd7733' },
      { name: 'dropsitenews', label: 'اخبار Drop Site', color: '#e63946' },
      { name: 'france24_en', label: 'فرانس ۲۴', color: '#2266bb' },
      { name: 'SaberinFa', label: 'صابرین (سپاه)', color: '#884422' },
      { name: 'defapress_ir', label: 'دفاپرس (وزارت دفاع)', color: '#556644' },
      { name: 'sepah', label: 'سپاه رسمی', color: '#774433' },
      { name: 'wamnews_en', label: 'WAM (امارات)', color: '#c4a535' },
      { name: 'gulfnewsUAE', label: 'اخبار خلیج', color: '#e6b800' },
      { name: 'Alibk3', label: 'علی BK', color: '#44bb88' },
      { name: 'aljazeeraglobal', label: 'الجزیره', color: '#d4a843' },
      { name: 'bintjbeilnews', label: 'اخبار بنت جبیل', color: '#55aa77' },
      { name: 'kianmeli1', label: 'کیان ملی (ایران)', color: '#7744aa' },
    ],

    ships: [
      { name: 'USS Bataan', hull: 'LHD-5', type: 'کشتی حمل‌و‌نقل برمبنای آمفی‌بیوس', class: 'کلاس Wasp', navy: 'نیروی دریایی ایالات‌متحده', lat: 26.1, lon: 50.5, status: 'مستقر', region: 'خلیج‌فارس', group: 'ناوگان پنجم' },
      { name: 'USS Mason', hull: 'DDG-87', type: 'ناوشکن', class: 'کلاس Arleigh Burke', navy: 'نیروی دریایی ایالات‌متحده', lat: 14.5, lon: 42.8, status: 'فعال', region: 'دریای سرخ', group: 'نیروی دریایی دریای سرخ' },
      { name: 'USS Carney', hull: 'DDG-64', type: 'ناوشکن', class: 'کلاس Arleigh Burke', navy: 'نیروی دریایی ایالات‌متحده', lat: 13.8, lon: 43.2, status: 'فعال', region: 'دریای سرخ', group: 'نیروی دریایی دریای سرخ' },
      { name: 'USS Laboon', hull: 'DDG-58', type: 'ناوشکن', class: 'کلاس Arleigh Burke', navy: 'نیروی دریایی ایالات‌متحده', lat: 25.8, lon: 52.1, status: 'مستقر', region: 'خلیج‌فارس', group: 'ناوگان پنجم' },
      { name: 'USS Philippine Sea', hull: 'CG-58', type: 'ناوشکن سریع', class: 'کلاس Ticonderoga', navy: 'نیروی دریایی ایالات‌متحده', lat: 25.2, lon: 56.8, status: 'مستقر', region: 'تنگه هرمز', group: 'گروه ناوبندی حامل ناو' },
      { name: 'USS Florida', hull: 'SSGN-728', type: 'زیردریایی موشک‌انداز', class: 'کلاس Ohio', navy: 'نیروی دریایی ایالات‌متحده', lat: 26.5, lon: 56.2, status: 'مستقر', region: 'تنگه هرمز', group: 'CENTCOM' },
      { name: 'HMS Diamond', hull: 'D34', type: 'ناوشکن', class: 'نوع ۴۵', navy: 'نیروی دریایی سلطنتی', lat: 14.2, lon: 42.5, status: 'فعال', region: 'دریای سرخ', group: 'عملیات حفاظت تجارت' },
      { name: 'FS Alsace', hull: 'D656', type: 'فریگات', class: 'کلاس FREMM', navy: 'نیروی دریایی فرانسه', lat: 34.5, lon: 33.2, status: 'مستقر', region: 'مدیترانه شرقی' },
      { name: 'INS Magen', hull: "Sa'ar 6", type: 'ناو کوچک', class: "کلاس Sa'ar 6", navy: 'نیروی دریایی اسرائیل', lat: 32.8, lon: 34.5, status: 'گشت‌وگذار', region: 'مدیترانه شرقی' },
      { name: 'INS Dolphin', hull: 'زیردریایی', type: 'زیردریایی', class: 'کلاس Dolphin', navy: 'نیروی دریایی اسرائیل', lat: 31.5, lon: 33.8, status: 'گشت‌وگذار', region: 'مدیترانه شرقی' },
      { name: 'IRIS Makran', hull: 'کشتی پایگاه پیشرو', type: 'کشتی پایگاه پیشرو', class: 'کلاس Makran', navy: 'نیروی دریایی ایران', lat: 25.4, lon: 57.5, status: 'فعال', region: 'تنگه هرمز' },
      { name: 'IRIS Sahand', hull: 'F-74', type: 'فریگات', class: 'کلاس Moudge', navy: 'نیروی دریایی ایران', lat: 27.1, lon: 56.3, status: 'فعال', region: 'خلیج‌فارس' },
      { name: 'IRGCN کشتی‌های سریع', hull: 'متنوع', type: 'کشتی حمله سریع', class: 'متنوع', navy: 'نیروی دریایی سپاه', lat: 26.8, lon: 56.1, status: 'فعال', region: 'تنگه هرمز', group: 'گشت‌وگذار سپاه' },
      { name: 'HMS Al Riyadh', hull: 'F-3000S', type: 'فریگات', class: 'کلاس Al Riyadh', navy: 'نیروی دریایی عربستان', lat: 20.5, lon: 39.8, status: 'گشت‌وگذار', region: 'دریای سرخ' },
    ],
    shipRegions: ['خلیج‌فارس', 'دریای سرخ', 'مدیترانه شرقی', 'دریای عرب'],

    alertProvider: 'سیستم هشدار اسرائیل',
    // هیچ منبع ردیابی پهپاد رایگان برای این تئاتر نیست
  },
};
